# https://goreleaser.com/customization/

# what to build
version: 2
builds:
  - env: ['CGO_ENABLED=0']
    flags: ['-trimpath']
    goos: ['darwin', 'linux', 'windows']
    goarch: ['amd64', 'arm64']
    ignore: [{ goos: 'windows', goarch: 'arm64' }]
    main: ./cmd

# what to put in the tgz files
archives:
  - files:
      - demo.gif
      - LICENSE
      - README.md
      - vectro.png
    format_overrides: [{ goos: 'windows', formats: ['zip'] }]
    wrap_in_directory: true

# turn stuff off
announce: { skip: true }
changelog: { disable: true }

# brew tap
brews:
  - repository: { owner: 'gurgeous', name: 'homebrew-tap' }
    description: The rpn calculator for your terminal.
    homepage: https://github.com/gurgeous/vectro
    test: system "#{bin}/vectro --version"
